#!/bin/bash
psql -U root -d postgre -c "CREATE DATABASE postgre;"
psql -U root -d postgre -c "CREATE TABLE IF NOT EXISTS orders_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255) NOT NULL,
  price DECIMAL NOT NULL,
  status VARCHAR(255),
  email VARCHAR(255) NOT NULL UNIQUE,
  CONSTRAINT pk_orders_table PRIMARY KEY (id)
);"