#!/bin/bash
psql -U root -d postgre -c "CREATE DATABASE IF NOT EXISTS postgre;"
psql -U root -d postgre -c "CREATE TABLE IF NOT EXISTS orders_table (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name VARCHAR(255),
  price DECIMAL,
  status VARCHAR(255),
  CONSTRAINT pk_orders_table PRIMARY KEY (id)
);"